name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "black[jupyter]" pytest

    - name: Lint with Black
      run: black --check .

    - name: Create sample data for CI
      run: |
        mkdir -p data
        echo "url,label" > data/sample_urls.csv
        echo "https://example.com,0" >> data/sample_urls.csv
        echo "http://phishingsite.ru/login,1" >> data/sample_urls.csv
        echo "https://google.com,0" >> data/sample_urls.csv
        echo "http://fakebank.com@realbank.com,1" >> data/sample_urls.csv

    - name: Train model
      run: python -m src.train

    - name: Evaluate model
      run: python -m src.evaluate

    - name: Run tests
      run: pytest -q --disable-warnings

    - name: Validate generated files
      run: |
        test -f models/baseline.joblib
        test -f data/processed.parquet
